# Generated by Django 6.0.1 on 2026-02-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texno', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
