# Generated by Django 6.0.1 on 2026-02-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texno', '0003_remove_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
